<!DOCTYPE html>

<html>
    <head>
            <meta charset="utf8">
            <title>FlowOne - Home </title>
            <link rel="stylesheet" href="~/Projetos/FlowOne/public/css/style.css">
             <script src="jquery.js"></script>
            <style>  </style> 
            
                     
    </head>
    <body>
            <div id="cabecalho">
                        <div id="area-logo"><h1>Flow<spam class="branco">One</spam></h1> 
                                
                        
                        </div>
                        

                        <div id="area-menu">    
                                        <a href="index.html">Follow-up</a>             
                                        <a href="receb.html">Recebimento</a>
                                        <a href="Dashboard/index.html">DashBoard</a>
                                        <a href="/login">Login</a>
                                        <a href="/inscreverse">Inscrever-se</a>
                                        
                        </div>  
                </div>
               
    </body>
</html>